import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border border-black sticky top-0 bg-white">
          <ul className="text-sm font-medium flex justify-between">
            <div className="flex *:border-l *:border-black *:px-9 *:py-4">
              <li>
                Shop
              </li>
              <li className="border-r border-black px-9 py-4">
                Contact
              </li>
            </div>
            <div className="flex *:border-l *:border-black *:px-9 *:py-4">
              <li>
                Sign in
              </li>
              <li>
                Cart
              </li>
            </div>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
